name: task_manager_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  intl: ^0.18.1
  uuid: ^4.5.2
  dotted_border: ^3.1.0
  flutter_slidable: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.0
  context_menus: ^2.0.0+1
  horizontal_week_calendar: ^0.0.7
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_login: ^4.2.1
  camera: ^0.11.3
  path_provider: ^2.1.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
